pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'thamibones/spa-booking:tests'
                    reuseNode true
                    alwaysPull true
                }
            }
            steps {
                dir("backend/tests"){
                   sh 'uv run --no-cache pytest -vv'
                }
            }
        }
    }
}
