pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'thamibones/spa-booking:tests'
                    reuseNode true
                }
            }
            environment {
                HOME = '/tmp'
            }
            steps {
                dir("backend/tests"){
                   sh 'uv run pytest -vv'
                }
            }
        }

        stage("Launch Backend") {
            agent {
                docker {
                    image 'docker:27.5.1'
                    reuseNode true
                    args '-v /var/run/docker.sock:/var/run/docker.sock -u 0'
                }
            }
            environment {
                DB_URL = credentials('DB_URL')
                DB_NAME = credentials('DB_NAME')
            }
            steps {
                dir("backend") {
                    sh 'docker compose up --build --wait'
                    sh 'docker compose logs server'
                }    
            }
            post {
                failure  {
                    dir("backend") {
                        sh 'docker compose logs server || true'
                        sh 'docker compose logs mongodb || true'
                    }
                }
            }
        }

        stage("API Tests") {
            agent {
                docker {
                    image 'thamibones/spa-booking:tests'
                    reuseNode true
                    args '-u 0 --network=host'
                }
            }
            environment {
                HOME = '/tmp'
                DB_URL = credentials('DB_URL')
                DB_NAME = credentials('DB_NAME')
            }          
            steps {
                dir("backend/tests_api") {
                    sh 'uv run pytest -vv'
                }
            }
        }

        stage('Deploy Backend Production') {
            when {
                expression {
                    return env.GIT_BRANCH == 'origin/master'
                }
            }
            agent {
                docker {
                    image 'ghcr.io/astral-sh/uv:python3.12-bookworm-slim'
                    reuseNode true
                }
            }
            environment {
                FASTAPI_CLOUD_TOKEN = credentials('fastapi-cloud-token')
                FASTAPI_CLOUD_APP_ID = credentials('fastapi-cloud-app-id')
                HOME = '/tmp'
            }
            steps {
                checkout scm
                dir("backend") {
                    sh 'uv sync --frozen'
                    sh 'uv run fastapi deploy'
                }
            }
        }

        stage ("Deploy Frontend Production") {
            when {
                expression {
                    return env.GIT_BRANCH == 'origin/master'
                }
            }
            agent {
                docker { 
                    image 'node:24-alpine3.23' 
                    args '-u root' 
                }
            }
            environment {
                NETLIFY_SITE_ID = credentials('netlify-site-id')
                NETLIFY_AUTH_TOKEN = credentials('netlify-auth-token')
                PNPM_HOME = '/root/.local/share/pnpm'
            }
            steps {
                checkout scm
                dir("frontend") {
                    sh '''
                        export PATH="$PNPM_HOME:$PATH"
                        corepack enable && corepack prepare pnpm@11 --activate
                        pnpm install netlify-cli -g
                        pnpm i --frozen-lockfile
                        pnpm build
                    '''
                    sh '''
                        netlify deploy \
                        --dir build \
                        --site "$NETLIFY_SITE_ID" \
                        --auth "$NETLIFY_AUTH_TOKEN" \
                        --message "Deploy from Jenkins" \
                        --prod
                    '''
                }
            }
           
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
