pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'thamibones/spa-booking:tests'
                    reuseNode true
                }
            }
            environment {
                HOME = '/tmp'
            }
            steps {
                dir("backend/tests"){
                   sh 'uv run pytest -vv'
                }
            }
        }

        stage("Launch Application") {
            agent {
                docker {
                    image 'docker:27.5.1'
                    reuseNode true
                    args '-v /var/run/docker.sock:/var/run/docker.sock -u 0'
                }
            }
            steps {
                dir("backend") {
                    sh 'docker compose up --build -d'
                }    
            }
        }
    }
}
